version: '3'
services:
  php:
    build:
      context: .
      dockerfile_inline: |
        FROM php:7.4-apache
        RUN docker-php-ext-install mysqli
    volumes:
      - ./www:/var/www/html
    ports:
      - 8082-8089:80
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - 8081:80
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - mysql
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile_inline: |
        FROM nginx:latest
        ARG CACHEBUST=1
        RUN echo "upstream loadbalancer {ip_hash;server php:80;}" > /etc/nginx/conf.d/default.conf
        RUN echo "server {location / {proxy_pass http://loadbalancer;}}" >> /etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
    - php
